### ISSUE TITLE
GTX 1080 rig crashed

### ISSUE THREAD

**Issue by GrasyPommel** [OhGodACompany/OhGodAnETHlargementPill#6]
This crashed my GTX 1080 mining rig. Use at your own risk because this tool is probably BS.

**Comment by OhGodAGirl** [comment]
If you had read the readme, you'd notice the comment about RevA and RevB - if your cards are crashing, you need to switch to --revA, because they likely have RevA memory. But I'm guessing you didn't.

**Comment by GrasyPommel** [comment]
It continues to crash every time I launch my miner with or without ETHlargement running.

**Comment by GrasyPommel** [comment]
Any advice? This tool completely broke my mining rig after running the program once. I've already deleted ETHlargement and the issue persists. I've reainstalled my miners and the issue persists. Rig crashes a few hours into mining now, despite being able to work stable for months before running this tool.

**Comment by jimmykl** [comment]
AFAIK the pill inserts some new memory timings for the driver/card but it's not permanent like a BIOS flash or anything, so not sure what could've gone wrong for your which wouldn't be solved with a restart. Maybe try a DDU?

**Comment by OhGodABird** [comment]
As @jimmykl mentioned, the changes are not permanent, and actually a lot more actions revert them than just a restart, that's why pills need to be continuously dosed in the background. If the issue still persists with pills not even being present, or worse, it starts to spread to other devices, I recommend double checking the kind of pills which were used initially, because they were likely something different than what's being discussed here.

**Comment by GrasyPommel** [comment]
I double checked. I download the correct files. The issues persist without them present, so they made some kind of permanent change elsewhere in the system whether the change was intentional or not. A clean reinstall of the graphics drivers did nothing.

**Comment by OhGodAGirl** [comment]
Look, man, I don't know what to tell you. The tool didn't break your mining rig. The tool didn't cause your wife to leave you. The tool didn't eat the last of your ham sandwhich. The tool isn't doing something malicious, and it's not the reason for your crashes.

Instead of blaming us, why don't you present a little more information, like, oh, I don't know:

Target OS
What Miner
Crash Logs
